
-- Create Roles for Provider and Consumer(Optional for testing the App within the provider account before publish)
-- ########## BEGIN ROLES (OPTIONAL)  ######################################
/*

USE ROLE ACCOUNTADMIN;

CREATE ROLE <ROLE_NAME>_PROVIDER_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE;
GRANT CREATE APPLICATION PACKAGE ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE;
GRANT CREATE APPLICATION  ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE ;
GRANT CREATE DATA EXCHANGE LISTING  ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE;
GRANT IMPORT SHARE ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE;
GRANT CREATE SHARE ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE;
GRANT MANAGE EVENT SHARING ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE;
GRANT CREATE DATA EXCHANGE LISTING ON ACCOUNT TO  ROLE <ROLE_NAME>_PROVIDER_ROLE; 
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE <ROLE_NAME>_PROVIDER_ROLE WITH GRANT OPTION;

GRANT ROLE <ROLE_NAME>_PROVIDER_ROLE to USER <USER_NAME>;

CREATE ROLE <ROLE_NAME>_CONSUMER_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE <ROLE_NAME>_CONSUMER_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE <ROLE_NAME>_CONSUMER_ROLE;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE <ROLE_NAME>_CONSUMER_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE <ROLE_NAME>_CONSUMER_ROLE;
GRANT CREATE APPLICATION  ON ACCOUNT TO ROLE <ROLE_NAME>_CONSUMER_ROLE ;
GRANT IMPORT SHARE ON ACCOUNT TO ROLE <ROLE_NAME>_CONSUMER_ROLE;
GRANT CREATE SHARE ON ACCOUNT TO ROLE <ROLE_NAME>_CONSUMER_ROLE;
GRANT MANAGE EVENT SHARING ON ACCOUNT TO ROLE <ROLE_NAME>_CONSUMER_ROLE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE <ROLE_NAME>_CONSUMER_ROLE WITH GRANT OPTION;

GRANT ROLE <ROLE_NAME>_CONSUMER_ROLE to USER <USER_NAME>;
