USE DATABASE NVIDIA_NEMO_MS_APP;
USE SCHEMA APP1;
-- CALL CORE.STOP_APP_INSTANCE('APP1');
-- CALL CORE.DROP_APP_INSTANCE('APP1');
-- CALL CORE.RESTART_APP_INSTANCE('APP1');
-- ALTER COMPUTE POOL APP1_NEW_GPU_COMPUTE_POOL_M RESUME; -- IF NOT ACTIVE RUN THIS COMMAND TO RESUME THE COMPUTE POOL 
-- APP1_NEW_GPU_COMPUTE_POOL_M
CALL CORE.LIST_APP_INSTANCE('APP1'); -- MAKE SURE ALL CONTAINERS ARE READY
CALL CORE.GET_APP_ENDPOINT('APP1'); -- GET APP ENDPOINTS TO ACCESS STREAMLIT APP
